#ifndef ALTAIR_BOARD_CONFIG_H
#define ALTAIR_BOARD_CONFIG_H

#include "driver/gpio.h"
#include "driver/spi_common.h"
#include "sdkconfig.h"

#define ALTAIR_ILI9341_PIN_MOSI 11
#define ALTAIR_ILI9341_PIN_SCLK 12
#define ALTAIR_ILI9341_PIN_CS 10
#define ALTAIR_ILI9341_PIN_DC 46
#define ALTAIR_ILI9341_PIN_RST -1
#define ALTAIR_ILI9341_PIN_BL 45
#define ALTAIR_ILI9341_SPI_HOST SPI2_HOST

#define ALTAIR_ST7305_PIN_DC GPIO_NUM_5
#define ALTAIR_ST7305_PIN_CS GPIO_NUM_40
#define ALTAIR_ST7305_PIN_SCK GPIO_NUM_11
#define ALTAIR_ST7305_PIN_MOSI GPIO_NUM_12
#define ALTAIR_ST7305_PIN_RST GPIO_NUM_41
#define ALTAIR_ST7305_SPI_HOST SPI3_HOST

#if CONFIG_ALTAIR_BOARD_FREENOVE

#define ALTAIR_BOARD_NAME "Freenove ESP32-S3"

#define ALTAIR_SDMMC_PIN_CLK 38
#define ALTAIR_SDMMC_PIN_CMD 40
#define ALTAIR_SDMMC_PIN_D0 39
#define ALTAIR_SDMMC_PIN_D1 41
#define ALTAIR_SDMMC_PIN_D2 48
#define ALTAIR_SDMMC_PIN_D3 47
#define ALTAIR_SDMMC_BUS_WIDTH 4

#elif CONFIG_ALTAIR_BOARD_WAVESHARE_RLCD

#define ALTAIR_BOARD_NAME "Waveshare ESP32-S3-RLCD-4.2"

#define ALTAIR_SDMMC_PIN_CLK 38
#define ALTAIR_SDMMC_PIN_CMD 21
#define ALTAIR_SDMMC_PIN_D0 39
#define ALTAIR_SDMMC_PIN_D1 -1
#define ALTAIR_SDMMC_PIN_D2 -1
#define ALTAIR_SDMMC_PIN_D3 -1
#define ALTAIR_SDMMC_BUS_WIDTH 1

#else
#error "Unsupported Altair board configuration"
#endif

#endif