#ifndef ALTAIR_BOARD_CONFIG_H
#define ALTAIR_BOARD_CONFIG_H

#include "driver/gpio.h"
#include "driver/spi_common.h"
#include "sdkconfig.h"

#define ALTAIR_ILI9341_PIN_MOSI 11
#define ALTAIR_ILI9341_PIN_SCLK 12
#define ALTAIR_ILI9341_PIN_CS 10
#define ALTAIR_ILI9341_PIN_DC 46
#define ALTAIR_ILI9341_PIN_RST -1
#define ALTAIR_ILI9341_PIN_BL 45
#define ALTAIR_ILI9341_SPI_HOST SPI2_HOST

#define ALTAIR_AXS15231B_PIN_CS GPIO_NUM_12
#define ALTAIR_AXS15231B_PIN_SCLK GPIO_NUM_5
#define ALTAIR_AXS15231B_PIN_DATA0 GPIO_NUM_1
#define ALTAIR_AXS15231B_PIN_DATA1 GPIO_NUM_2
#define ALTAIR_AXS15231B_PIN_DATA2 GPIO_NUM_3
#define ALTAIR_AXS15231B_PIN_DATA3 GPIO_NUM_4
#define ALTAIR_AXS15231B_PIN_RST GPIO_NUM_NC
#define ALTAIR_AXS15231B_PIN_BL GPIO_NUM_6
#define ALTAIR_AXS15231B_SPI_HOST SPI2_HOST

#if CONFIG_ALTAIR_BOARD_FREENOVE

#define ALTAIR_BOARD_NAME "Freenove ESP32-S3"

#define ALTAIR_SD_CARD_USE_SDMMC 1

#define ALTAIR_SDMMC_PIN_CLK 38
#define ALTAIR_SDMMC_PIN_CMD 40
#define ALTAIR_SDMMC_PIN_D0 39
#define ALTAIR_SDMMC_PIN_D1 41
#define ALTAIR_SDMMC_PIN_D2 48
#define ALTAIR_SDMMC_PIN_D3 47
#define ALTAIR_SDMMC_BUS_WIDTH 4
#define ALTAIR_STATUS_LED_GPIO 42

#elif CONFIG_ALTAIR_BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_3_5B

#define ALTAIR_BOARD_NAME "WAVESHARE-ESP32-S3-Touch-LCD-3.5B"

#define ALTAIR_SD_CARD_USE_SDMMC 1

#define ALTAIR_SDMMC_PIN_CLK 11
#define ALTAIR_SDMMC_PIN_CMD 10
#define ALTAIR_SDMMC_PIN_D0 9
#define ALTAIR_SDMMC_PIN_D1 -1
#define ALTAIR_SDMMC_PIN_D2 -1
#define ALTAIR_SDMMC_PIN_D3 -1
#define ALTAIR_SDMMC_BUS_WIDTH 1
#define ALTAIR_STATUS_LED_GPIO 42

#elif CONFIG_ALTAIR_BOARD_LONELY_BINARY_ALTAIR_KIT

#define ALTAIR_BOARD_NAME "Lonely Binary Altair Kit"

#define ALTAIR_HAS_FRONT_PANEL_KIT 1

#define ALTAIR_FRONT_PANEL_KIT_SWITCH_LOAD_GPIO GPIO_NUM_42
#define ALTAIR_FRONT_PANEL_KIT_SWITCH_CS_GPIO GPIO_NUM_9
#define ALTAIR_FRONT_PANEL_KIT_MISO_GPIO GPIO_NUM_5
#define ALTAIR_FRONT_PANEL_KIT_MOSI_GPIO GPIO_NUM_4
#define ALTAIR_FRONT_PANEL_KIT_RESET_GPIO GPIO_NUM_39
#define ALTAIR_FRONT_PANEL_KIT_CLK_GPIO GPIO_NUM_1
#define ALTAIR_FRONT_PANEL_KIT_LED_STORE_GPIO GPIO_NUM_40
#define ALTAIR_FRONT_PANEL_KIT_LED_OE_GPIO GPIO_NUM_8
#define ALTAIR_FRONT_PANEL_KIT_SPI_HOST SPI3_HOST

#define ALTAIR_SD_CARD_USE_SDSPI 1

#define ALTAIR_SDSPI_HOST SPI3_HOST
#define ALTAIR_SDSPI_PIN_MOSI 4
#define ALTAIR_SDSPI_PIN_MISO 5
#define ALTAIR_SDSPI_PIN_SCLK 6
#define ALTAIR_SDSPI_PIN_CS 7
#define ALTAIR_SDSPI_MAX_FREQ_KHZ 12000
#define ALTAIR_STATUS_LED_GPIO 48

#elif CONFIG_ALTAIR_BOARD_SEEED_XIAO_ESP32_S3

#define ALTAIR_BOARD_NAME "Seeed XIAO ESP32-S3 Altair Kit"

#define ALTAIR_HAS_FRONT_PANEL_KIT 1

#define ALTAIR_FRONT_PANEL_KIT_SWITCH_LOAD_GPIO GPIO_NUM_1
#define ALTAIR_FRONT_PANEL_KIT_SWITCH_CS_GPIO GPIO_NUM_2
#define ALTAIR_FRONT_PANEL_KIT_MISO_GPIO GPIO_NUM_8
#define ALTAIR_FRONT_PANEL_KIT_MOSI_GPIO GPIO_NUM_9
#define ALTAIR_FRONT_PANEL_KIT_RESET_GPIO GPIO_NUM_4
#define ALTAIR_FRONT_PANEL_KIT_CLK_GPIO GPIO_NUM_7
#define ALTAIR_FRONT_PANEL_KIT_LED_STORE_GPIO GPIO_NUM_5
#define ALTAIR_FRONT_PANEL_KIT_LED_OE_GPIO GPIO_NUM_6
#define ALTAIR_FRONT_PANEL_KIT_SPI_HOST SPI3_HOST

#define ALTAIR_SD_CARD_USE_SDSPI 1

#define ALTAIR_SDSPI_HOST SPI3_HOST
#define ALTAIR_SDSPI_PIN_MOSI 9
#define ALTAIR_SDSPI_PIN_MISO 8
#define ALTAIR_SDSPI_PIN_SCLK 7
#define ALTAIR_SDSPI_PIN_CS 10
#define ALTAIR_SDSPI_MAX_FREQ_KHZ 12000
#define ALTAIR_STATUS_LED_GPIO 21
#define ALTAIR_STATUS_LED_IS_WS2812 0
#define ALTAIR_STATUS_LED_ACTIVE_LOW 1

#else
#error "Unsupported Altair board configuration"
#endif

#ifndef ALTAIR_HAS_FRONT_PANEL_KIT
#define ALTAIR_HAS_FRONT_PANEL_KIT 0
#endif

#ifndef ALTAIR_STATUS_LED_IS_WS2812
#define ALTAIR_STATUS_LED_IS_WS2812 1
#endif

#ifndef ALTAIR_STATUS_LED_ACTIVE_LOW
#define ALTAIR_STATUS_LED_ACTIVE_LOW 0
#endif

#endif